name: github-ci

on:
  pull_request:
    branches:
      - develop
  push: 
    branches: 
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Copy environment file
        run: cp .env.example ./backend/.env

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Set database data
        working-directory: ./backend
        run: |
          python manage.py migrate

      - name: Run Tests
        working-directory: ./backend
        run: |
          pytest
  
  build:
    runs-on: ubuntu-latest

    env:
      FRONTEND_APP_NAME: "devops-project-frontend"
      BACKEND_APP_NAME: "devops-project-backend"

    steps:
      - uses: actions/checkout@v4

      - name: Build frontend container
        working-directory: ./frontend
        run: |
          docker build -t ${{ env.FRONTEND_APP_NAME }} ./

      - name: Build backend container
        working-directory: ./backend
        run: |
          docker build -t ${{ env.BACKEND_APP_NAME }} ./
